# Generated by Django 5.2.4 on 2026-01-04 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_initial"),
        ("receivables", "0002_initial"),
        ("sales", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="billing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="receivables.payment",
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequences",
                to="tenants.business",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("business", "invoice_number"), name="uniq_invoice_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("business", "receipt_number"), name="uniq_receipt_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="sequence",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="uniq_sequence_name"
            ),
        ),
    ]
