# Generated by Django 5.2.4 on 2026-01-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("issued", "Em aberto"),
                    ("partial", "Parcialmente paga"),
                    ("paid", "Paga"),
                    ("canceled", "Cancelada"),
                ],
                default="issued",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("method", models.CharField(choices=[("cash", "Dinheiro"), ("card", "Cartao"), ("bank_transfer", "Transferencia"), ("cheque", "Cheque"), ("mpesa", "MPesa"), ("emola", "Emola"), ("mkesh", "MKesh"), ("other", "Outro")], max_length=20)),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoice_payments", to="tenants.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoice_payments", to=settings.AUTH_USER_MODEL)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="billing.invoice")),
            ],
            options={
                "indexes": [models.Index(fields=["business", "invoice"], name="billing_invo_business_bf0c70_idx")],
            },
        ),
        migrations.AddField(
            model_name="receipt",
            name="invoice_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="billing.invoicepayment",
            ),
        ),
    ]
