# Generated by Django 5.2.4 on 2026-01-11

from decimal import Decimal

from django.db import migrations
from django.db.models import Sum


def backfill_invoice_status(apps, schema_editor):
    Invoice = apps.get_model("billing", "Invoice")
    InvoicePayment = apps.get_model("billing", "InvoicePayment")
    Payment = apps.get_model("receivables", "Payment")

    for invoice in Invoice.objects.all():
        if invoice.status == "canceled":
            continue
        total_paid = (
            InvoicePayment.objects.filter(invoice_id=invoice.id)
            .aggregate(total=Sum("amount"))
            .get("total")
            or Decimal("0")
        )
        if invoice.sale_id:
            total_paid += (
                Payment.objects.filter(receivable__sale_id=invoice.sale_id)
                .aggregate(total=Sum("amount"))
                .get("total")
                or Decimal("0")
            )
        if total_paid >= invoice.total:
            invoice.status = "paid"
        elif total_paid > 0:
            invoice.status = "partial"
        else:
            invoice.status = "issued"
        invoice.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_invoice_payments"),
        ("receivables", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_invoice_status, migrations.RunPython.noop),
    ]
