# Generated by Django 5.2.4 on 2026-01-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_status_backfill'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoicepayment',
            new_name='billing_inv_busines_517701_idx',
            old_name='billing_invo_business_bf0c70_idx',
        ),
    ]
