# Generated by Django 5.2.4 on 2026-01-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_payment_methods'),
        ('billing', '0008_sync_invoice_payments_to_receivables'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customerpaymentmethod'),
        ),
    ]
