# Generated by Django 5.2.4 on 2026-01-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
