# Generated by Django 5.2.4 on 2026-01-12 19:22

from django.db import migrations


def fill_payment_snapshot(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    Business = apps.get_model('tenants', 'Business')
    TenantMobileWallet = apps.get_model('tenants', 'TenantMobileWallet')
    TenantBankAccount = apps.get_model('tenants', 'TenantBankAccount')

    businesses = Business.objects.all()
    snapshots = {}
    wallet_labels = {
        'mpesa': 'M-Pesa',
        'mkesh': 'M-Kesh',
        'emola': 'e-Mola',
    }

    for business in businesses:
        wallets = list(
            TenantMobileWallet.objects.filter(business=business, is_active=True)
            .order_by('id')
            .values('wallet_type', 'holder_name', 'phone_number')
        )
        wallet_payload = []
        for wallet in wallets:
            wallet_payload.append(
                {
                    'type': wallet['wallet_type'],
                    'label': wallet_labels.get(wallet['wallet_type'], wallet['wallet_type']),
                    'holder_name': wallet['holder_name'],
                    'phone_number': wallet['phone_number'],
                }
            )
        banks = list(
            TenantBankAccount.objects.filter(business=business, is_active=True)
            .order_by('id')
            .values('bank_name', 'account_number', 'nib', 'holder_name')
        )
        bank_payload = []
        for bank in banks:
            bank_payload.append(
                {
                    'bank_name': bank['bank_name'],
                    'account_number': bank['account_number'],
                    'nib': bank['nib'],
                    'holder_name': bank['holder_name'],
                }
            )
        snapshots[business.id] = {'wallets': wallet_payload, 'banks': bank_payload}

    for invoice in Invoice.objects.all().iterator():
        if invoice.payment_snapshot:
            continue
        snapshot = snapshots.get(invoice.business_id, {'wallets': [], 'banks': []})
        invoice.payment_snapshot = snapshot
        invoice.save(update_fields=['payment_snapshot'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_payment_snapshot'),
        ('tenants', '0008_tenant_payment_data'),
    ]

    operations = [
        migrations.RunPython(fill_payment_snapshot, noop_reverse),
    ]
