# Generated by Django 5.2.4 on 2026-01-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_fill_invoice_payment_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Numerario'), ('card', 'Cartao'), ('bank_transfer', 'Transferencia'), ('cheque', 'Cheque'), ('mpesa', 'MPesa'), ('emola', 'Emola'), ('mkesh', 'MKesh'), ('other', 'Outro')], max_length=20),
        ),
    ]
