# Generated by Django 5.2.4 on 2026-01-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='finance_cas_busines_d6630f_idx',
            old_name='finance_cash_business_bf6f70_idx',
        ),
    ]
