# Generated by Django 5.2.4 on 2026-01-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financial_accounts_and_methods'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='finance_cas_busines_23a48a_idx',
            old_name='finance_cash_business_category_idx',
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartao'), ('bank_transfer', 'Transferencia'), ('cheque', 'Cheque'), ('mpesa', 'MPesa'), ('emola', 'Emola'), ('mkesh', 'MKesh'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('card', 'Cartao'), ('bank_transfer', 'Transferencia'), ('cheque', 'Cheque'), ('mpesa', 'MPesa'), ('emola', 'Emola'), ('mkesh', 'MKesh'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('card', 'Cartao'), ('bank_transfer', 'Transferencia'), ('cheque', 'Cheque'), ('mpesa', 'MPesa'), ('emola', 'Emola'), ('mkesh', 'MKesh'), ('other', 'Outro')], max_length=20),
        ),
    ]
