# Generated by Django 5.2.4 on 2026-01-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_rename_cash_method_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='method',
            field=models.CharField(choices=[('cash', 'Numerario'), ('card', 'Cartao'), ('bank_transfer', 'Transferencia'), ('cheque', 'Cheque'), ('mpesa', 'MPesa'), ('emola', 'Emola'), ('mkesh', 'MKesh'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Numerario'), ('card', 'Cartao'), ('bank_transfer', 'Transferencia'), ('cheque', 'Cheque'), ('mpesa', 'MPesa'), ('emola', 'Emola'), ('mkesh', 'MKesh'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Numerario'), ('card', 'Cartao'), ('bank_transfer', 'Transferencia'), ('cheque', 'Cheque'), ('mpesa', 'MPesa'), ('emola', 'Emola'), ('mkesh', 'MKesh'), ('other', 'Outro')], max_length=20),
        ),
    ]
