# Generated by Codex on 2026-01-14

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_cashmovement_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                condition=Q(("code__isnull", False)),
                fields=("business", "code"),
                name="uniq_purchase_code_business",
            ),
        ),
    ]
