# Generated by Codex on 2026-01-14

from django.db import migrations
from django.db.models import Q


def backfill_purchase_codes(apps, schema_editor):
    Purchase = apps.get_model("finance", "Purchase")
    DocumentSequence = apps.get_model("tenants", "DocumentSequence")
    db_alias = schema_editor.connection.alias

    purchases = (
        Purchase.objects.using(db_alias)
        .filter(Q(code__isnull=True) | Q(code=""))
        .order_by("purchase_date", "id")
    )
    for purchase in purchases:
        seq, _ = DocumentSequence.objects.using(db_alias).get_or_create(
            business_id=purchase.business_id,
            doc_type="purchase",
            seq_date=purchase.purchase_date,
            defaults={"current_value": 0},
        )
        seq.current_value += 1
        seq.save(update_fields=["current_value"])
        code = f"C-{purchase.purchase_date.strftime('%y%m%d')}-{purchase.business_id}-{seq.current_value:03d}"
        purchase.code = code
        purchase.save(update_fields=["code"])


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_purchase_code"),
        ("tenants", "0010_document_sequence"),
    ]

    operations = [
        migrations.RunPython(backfill_purchase_codes, reverse_noop),
    ]
