# Generated by Django 5.2.4 on 2026-01-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_purchase_stock_received'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchasepayment',
            new_name='finance_pur_busines_9df87a_idx',
            old_name='finance_purc_busines_6db6f9_idx',
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
