# Generated by Django 5.2.4 on 2026-01-04 20:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.16"), max_digits=5
            ),
        ),
    ]
