# Generated by Django 5.2.4 on 2026-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_business_feature_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('general', 'Negocio geral'), ('hardware', 'Ferragem / construcao'), ('workshop', 'Oficina mecanica'), ('restaurant', 'Restaurante (servico a mesa)'), ('burger', 'Hamburgueria (fast-casual)'), ('grocery', 'Mini-mercearia / cantina'), ('mini_grocery', 'Mini-mercearia (novo)'), ('clothing', 'Loja de roupa'), ('electric', 'Material eletrico / mecanico'), ('alcohol_stall', 'Barraca de bebidas')], default='general', max_length=30),
        ),
    ]
