# Generated by Django 5.2.4 on 2026-01-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_payment_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantbankaccount',
            new_name='tenants_ten_busines_f76f8d_idx',
            old_name='tenants_ten_business_b1eaa5_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantmobilewallet',
            new_name='tenants_ten_busines_556ad1_idx',
            old_name='tenants_ten_business_0b5400_idx',
        ),
    ]
