# Generated by Django 5.2.4 on 2026-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_business_allow_over_delivery_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='doc_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('invoice', 'Fatura'), ('receipt', 'Recibo'), ('delivery', 'Guia de entrega'), ('purchase', 'Compra'), ('quotation', 'Cotacao')], max_length=20),
        ),
    ]
