# Generated by Django 5.2.4 on 2026-01-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_roles_and_membership_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roleauditlog',
            new_name='tenants_rol_busines_5c44e6_idx',
            old_name='tenants_ro_business_8c1d7f_idx',
        ),
    ]
