# Generated by Django 5.2.4 on 2026-01-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_business_approval_and_email_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantemaillog',
            new_name='tenants_ten_busines_c715dc_idx',
            old_name='tenants_ten_business_d9b7b9_idx',
        ),
    ]
