# Generated by Django 5.2.4 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_rename_tenants_ten_business_d9b7b9_idx_tenants_ten_busines_c715dc_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("sale", "Venda"),
                    ("invoice", "Fatura"),
                    ("receipt", "Recibo"),
                    ("delivery", "Guia de entrega"),
                    ("purchase", "Compra"),
                    ("quotation", "Cotacao"),
                    ("expense", "Despesa"),
                ],
                max_length=20,
            ),
        ),
    ]
