# Generated by Django 5.2.4 on 2026-02-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_alter_documentsequence_doc_type_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("sale", "Venda"),
                    ("order", "Pedido"),
                    ("invoice", "Fatura"),
                    ("receipt", "Recibo"),
                    ("delivery", "Guia de entrega"),
                    ("purchase", "Compra"),
                    ("quotation", "Cotacao"),
                    ("expense", "Despesa"),
                ],
                max_length=20,
            ),
        ),
    ]
