# Generated by Django 5.2 on 2026-04-08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0018_alter_documentsequence_doc_type_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.CharField(choices=[("info", "Informacao"), ("warning", "Aviso"), ("critical", "Critico")], default="info", max_length=20)),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="platform_alerts", to="tenants.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_platform_alerts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["is_active", "level"], name="superadmin__is_acti_245ba1_idx")],
            },
        ),
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_platform_settings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("price_monthly", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                ("billing_cycle_months", models.PositiveIntegerField(default=1)),
                ("trial_days", models.PositiveIntegerField(default=14)),
                ("max_users", models.PositiveIntegerField(blank=True, null=True)),
                ("max_branches", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_subscription_plans", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_subscription_plans", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SuperAdminAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=120)),
                ("target_type", models.CharField(blank=True, max_length=80)),
                ("target_id", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="superadmin_audit_logs", to=settings.AUTH_USER_MODEL)),
                ("business", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="superadmin_audit_logs", to="tenants.business")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="superadmin__created_c3c9b5_idx"),
                    models.Index(fields=["action"], name="superadmin__action_db7324_idx"),
                    models.Index(fields=["target_type", "target_id"], name="superadmin__target__0a9a34_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=160)),
                ("message", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Aberto"), ("in_progress", "Em progresso"), ("resolved", "Resolvido")], default="open", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_support_tickets", to=settings.AUTH_USER_MODEL)),
                ("business", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="support_tickets", to="tenants.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_support_tickets", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status", "created_at"], name="superadmin__status_c6b223_idx")],
            },
        ),
        migrations.CreateModel(
            name="TenantAdminNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note_type", models.CharField(choices=[("general", "Geral"), ("billing", "Faturacao"), ("support", "Suporte"), ("risk", "Risco")], default="general", max_length=20)),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="superadmin_notes", to="tenants.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_tenant_admin_notes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["business", "created_at"], name="superadmin__busines_a029ec_idx")],
            },
        ),
        migrations.CreateModel(
            name="TenantStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="tenants.business")),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tenant_status_changes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [models.Index(fields=["business", "changed_at"], name="superadmin__busines_4ee427_idx")],
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("trial", "Trial"), ("active", "Ativa"), ("expired", "Expirada"), ("suspended", "Suspensa"), ("canceled", "Cancelada")], default="trial", max_length=20)),
                ("started_at", models.DateField(default=django.utils.timezone.localdate)),
                ("trial_ends_at", models.DateField(blank=True, null=True)),
                ("ends_at", models.DateField(blank=True, null=True)),
                ("next_renewal_at", models.DateField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=False)),
                ("payment_proof_status", models.CharField(choices=[("none", "Sem comprovativo"), ("pending", "Pendente"), ("approved", "Aprovado"), ("rejected", "Rejeitado")], default="none", max_length=20)),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                ("last_payment_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to="tenants.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_tenant_subscriptions", to=settings.AUTH_USER_MODEL)),
                ("plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscriptions", to="superadmin.subscriptionplan")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_tenant_subscriptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["business__name"],
                "indexes": [
                    models.Index(fields=["status", "ends_at"], name="superadmin__status_7f5030_idx"),
                    models.Index(fields=["payment_proof_status"], name="superadmin__payment_4731c8_idx"),
                ],
            },
        ),
    ]
