# Generated by Django 5.2.4 on 2026-01-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_finance_cash_business_category_idx_finance_cas_busines_23a48a_idx_and_more'),
        ('inventory', '0002_goods_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='cash_movement',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='goods_receipt',
                to='finance.cashmovement',
            ),
        ),
    ]
