# Generated by Django 5.2.4 on 2026-01-13 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_goodsreceipt_cash_movement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='goodsreceipt',
            new_name='inventory_g_busines_1964a9_idx',
            old_name='inventory_g_busines_18f4f2_idx',
        ),
        migrations.RenameIndex(
            model_name='goodsreceipt',
            new_name='inventory_g_busines_da7a7c_idx',
            old_name='inventory_g_busines_7d696d_idx',
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
