# Generated by Django 5.2.4 on 2026-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_goodsreceipt_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saida'), ('ADJUST', 'Ajuste'), ('RESERVE', 'Reserva')], max_length=10),
        ),
    ]
