# Generated by Django 5.2.4 on 2026-01-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_report_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportaccess',
            options={'permissions': (('view_basic', 'Pode ver relatorios basicos'), ('view_finance', 'Pode ver relatorios financeiros'), ('view_stock', 'Pode ver relatorios de stock'), ('export', 'Pode exportar relatorios'))},
        ),
    ]
