# Generated by Django 5.2.4 on 2026-01-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_payment_methods'),
        ('billing', '0010_invoice_payment_snapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPaymentMethod',
        ),
    ]
