# Generated by Django 5.2.4 on 2026-04-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_reorder_level_integer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("size", models.CharField(blank=True, max_length=30)),
                ("color", models.CharField(blank=True, max_length=30)),
                ("sku", models.CharField(blank=True, max_length=60)),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("stock_qty", models.IntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="catalog_pro_product_6c5ee9_idx",
                    ),
                    models.Index(
                        fields=["product", "stock_qty"],
                        name="catalog_pro_product_14c1dc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "name", "size", "color"),
                        name="uniq_product_variant_identity",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("sku__isnull", False), models.Q(("sku", ""), _negated=True)
                        ),
                        fields=("product", "sku"),
                        name="uniq_variant_sku_per_product",
                    ),
                ],
            },
        ),
    ]
