# Generated by Django 5.2.4 on 2026-01-29 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='food_order_busines_6736c3_idx',
            old_name='food_order_busines_2f6508_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='food_order_busines_efd9eb_idx',
            old_name='food_order_busines_77e3e8_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_food_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_food_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
