# Generated by Django 5.2.4 on 2026-02-01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_rename_food_order_busines_2f6508_idx_food_order_busines_6736c3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Nao pago"), ("partial", "Parcial"), ("paid", "Pago")],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("confirmed", "Confirmado"),
                    ("in_preparation", "Em preparacao"),
                    ("ready", "Pronto"),
                    ("delivered", "Entregue"),
                    ("canceled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="channel",
            field=models.CharField(
                choices=[
                    ("dine_in", "Mesa"),
                    ("take_away", "Take away"),
                    ("delivery", "Delivery"),
                ],
                default="dine_in",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FoodExtra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("extra_type", models.CharField(choices=[("extra", "Extra"), ("variant", "Variante")], default="extra", max_length=20)),
                ("extra_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("business", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="food_extras", to="tenants.business")),
            ],
        ),
        migrations.CreateModel(
            name="OrderItemExtra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("extra", models.ForeignKey(on_delete=models.deletion.PROTECT, to="food.foodextra")),
                ("order_item", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="extras", to="food.orderitem")),
            ],
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("method", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_at", models.DateTimeField()),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="food_payments", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="payments", to="food.order")),
            ],
        ),
        migrations.AddIndex(
            model_name="foodextra",
            index=models.Index(fields=["business", "extra_type"], name="food_foodex_business_9e6b7b_idx"),
        ),
    ]
