# Generated by Django 5.2.4 on 2026-02-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_order_payment_fields_and_extras"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodIngredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("stock_qty", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="food_ingredients", to="tenants.business")),
            ],
        ),
        migrations.CreateModel(
            name="FoodRecipeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("ingredient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipes", to="food.foodingredient")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="food_recipe", to="catalog.product")),
            ],
        ),
        migrations.AddIndex(
            model_name="foodingredient",
            index=models.Index(fields=["business", "name"], name="food_foodingredient_business_4f9caa_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="foodingredient",
            unique_together={("business", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="foodrecipeitem",
            unique_together={("product", "ingredient")},
        ),
    ]
