# Generated by Django 5.2.4 on 2026-02-01

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    Order = apps.get_model("food", "Order")
    Order.objects.filter(status="in_kitchen").update(status="in_preparation")
    Order.objects.filter(status="paid").update(status="confirmed")
    Order.objects.filter(channel="counter").update(channel="dine_in")
    Order.objects.filter(channel="takeaway").update(channel="take_away")


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_food_ingredients"),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, migrations.RunPython.noop),
    ]
