# Generated by Django 5.2.4 on 2026-02-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_migrate_order_statuses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='foodextra',
            new_name='food_foodex_busines_a427f2_idx',
            old_name='food_foodex_business_9e6b7b_idx',
        ),
        migrations.RenameIndex(
            model_name='foodingredient',
            new_name='food_foodin_busines_d8d446_idx',
            old_name='food_foodingredient_business_4f9caa_idx',
        ),
    ]
