# Generated by Codex on 2026-02-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_rename_food_foodex_business_9e6b7b_idx_food_foodex_busines_a427f2_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="menu_categories", to="tenants.business")),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("item_type", models.CharField(choices=[("food", "Comida"), ("beverage", "Bebida")], default="food", max_length=20)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("image", models.ImageField(blank=True, null=True, upload_to="menu_items/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="menu_items", to="tenants.business")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="food.menucategory")),
                ("ingredient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="beverage_items", to="food.foodingredient")),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemRecipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("ingredient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipes", to="food.foodingredient")),
                ("menu_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipes", to="food.menuitem")),
            ],
        ),
        migrations.CreateModel(
            name="IngredientStockEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("supplier_name", models.CharField(blank=True, max_length=120)),
                ("reference_number", models.CharField(blank=True, max_length=80)),
                ("entry_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ingredient_entries", to="tenants.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_ingredient_entries", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="IngredientStockEntryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="food.ingredientstockentry")),
                ("ingredient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="food.foodingredient")),
            ],
        ),
        migrations.CreateModel(
            name="IngredientMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("movement_type", models.CharField(choices=[("in", "Entrada"), ("out", "Saida"), ("adjust", "Ajuste")], max_length=20)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("reference_type", models.CharField(blank=True, max_length=30)),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ingredient_movements", to="tenants.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ingredient_movements", to=settings.AUTH_USER_MODEL)),
                ("ingredient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="food.foodingredient")),
            ],
        ),
        migrations.AddField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="food.menuitem"),
        ),
        migrations.AlterUniqueTogether(
            name="menucategory",
            unique_together={("business", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="menuitem",
            unique_together={("business", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="menuitemrecipe",
            unique_together={("menu_item", "ingredient")},
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["business", "name"], name="food_menuitem_business_7d6b65_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["business", "item_type"], name="food_menuitem_business_5b4a2b_idx"),
        ),
        migrations.AddIndex(
            model_name="ingredientmovement",
            index=models.Index(fields=["business", "created_at"], name="food_ingredien_business_0b7d28_idx"),
        ),
        migrations.AddIndex(
            model_name="ingredientmovement",
            index=models.Index(fields=["business", "ingredient"], name="food_ingredien_business_e2b2b4_idx"),
        ),
        migrations.DeleteModel(
            name="FoodRecipeItem",
        ),
    ]
