# Generated by Django 5.2.4 on 2026-04-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_reorder_level_integer'),
        ('food', '0007_menu_items_and_ingredients_stock'),
        ('tenants', '0018_alter_documentsequence_doc_type_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingredientmovement',
            new_name='food_ingred_busines_8d9bce_idx',
            old_name='food_ingredien_business_0b7d28_idx',
        ),
        migrations.RenameIndex(
            model_name='ingredientmovement',
            new_name='food_ingred_busines_cca4f0_idx',
            old_name='food_ingredien_business_e2b2b4_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='food_menuit_busines_1f137d_idx',
            old_name='food_menuitem_business_7d6b65_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='food_menuit_busines_e45fec_idx',
            old_name='food_menuitem_business_5b4a2b_idx',
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['business', 'name'], name='food_menuca_busines_04fd85_idx'),
        ),
    ]
