# Generated by Django 5.2.4 on 2026-04-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "food",
            "0008_rename_food_ingredien_business_0b7d28_idx_food_ingred_busines_8d9bce_idx_and_more",
        ),
        ("tenants", "0018_alter_documentsequence_doc_type_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("seats", models.PositiveIntegerField(default=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Livre"),
                            ("occupied", "Ocupada"),
                            ("reserved", "Reservada"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_tables",
                        to="tenants.business",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="food.restauranttable",
            ),
        ),
        migrations.AddIndex(
            model_name="restauranttable",
            index=models.Index(
                fields=["business", "status"], name="food_restau_busines_e3ba53_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="restauranttable",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="uniq_restaurant_table_name_business"
            ),
        ),
    ]
