# Generated by Django 5.2.4 on 2026-04-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0009_restauranttable_order_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restauranttable",
            name="reserved_for",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="restauranttable",
            name="reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
