# Generated by Codex on 2026-01-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.core.validators
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_reorder_level_integer"),
        ("customers", "0004_customer_profile_fields"),
        ("sales", "0009_sale_code"),
        ("tenants", "0010_document_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, max_length=30, null=True)),
                ("status", models.CharField(choices=[("draft", "Rascunho"), ("sent", "Enviada"), ("approved", "Aprovada"), ("rejected", "Rejeitada"), ("expired", "Expirada"), ("canceled", "Cancelada")], default="draft", max_length=20)),
                ("issue_date", models.DateField(default=django.utils.timezone.localdate)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="MZN", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount_type", models.CharField(choices=[("none", "Sem desconto"), ("fixed", "Valor fixo"), ("percent", "Percentagem")], default="none", max_length=10)),
                ("discount_value", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("payment_snapshot", models.JSONField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_quotations", to=settings.AUTH_USER_MODEL)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quotations", to="tenants.business")),
                ("canceled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="canceled_quotations", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_quotations", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quotations", to="customers.customer")),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rejected_quotations", to=settings.AUTH_USER_MODEL)),
                ("sale", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quotation", to="sales.sale")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_quotations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["business", "status", "issue_date"], name="quotations_busi_1dfb0b_idx")],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_rate", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("line_subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_tax", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quotation_items", to="catalog.product")),
                ("quotation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="quotations.quotation")),
            ],
            options={
                "indexes": [models.Index(fields=["quotation", "product"], name="quotations_quo_6c3d8c_idx")],
            },
        ),
        migrations.CreateModel(
            name="QuotationStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Rascunho"), ("sent", "Enviada"), ("approved", "Aprovada"), ("rejected", "Rejeitada"), ("expired", "Expirada"), ("canceled", "Cancelada")], max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quotation_status_changes", to=settings.AUTH_USER_MODEL)),
                ("quotation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="quotations.quotation")),
            ],
            options={
                "indexes": [models.Index(fields=["quotation", "changed_at"], name="quotations_quo_edd1f9_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(condition=Q(("code__isnull", False)), fields=("business", "code"), name="uniq_quotation_code_business"),
        ),
    ]
