# Generated by Django 5.2.4 on 2026-01-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quotation',
            new_name='quotations__busines_d0b21d_idx',
            old_name='quotations_busi_1dfb0b_idx',
        ),
        migrations.RenameIndex(
            model_name='quotationitem',
            new_name='quotations__quotati_60ddb5_idx',
            old_name='quotations_quo_6c3d8c_idx',
        ),
        migrations.RenameIndex(
            model_name='quotationstatushistory',
            new_name='quotations__quotati_a76944_idx',
            old_name='quotations_quo_edd1f9_idx',
        ),
    ]
