# Generated by Django 5.2.4 on 2026-01-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("receivables", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivable",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivables",
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="receivable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="receivables.receivable",
            ),
        ),
        migrations.AddIndex(
            model_name="receivable",
            index=models.Index(
                fields=["business", "status"], name="receivables_busines_079d67_idx"
            ),
        ),
    ]
