# Generated by Django 5.2.4 on 2026-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0003_sync_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartao'), ('bank_transfer', 'Transferencia'), ('cheque', 'Cheque'), ('mpesa', 'MPesa'), ('emola', 'Emola'), ('mkesh', 'MKesh'), ('other', 'Outro')], default='cash', max_length=20),
        ),
    ]
