# Generated by Django 5.2.4 on 2026-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_returns_and_refunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_mode',
            field=models.CharField(choices=[('immediate', 'Levantamento imediato'), ('scheduled', 'Levantamento faseado')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcialmente entregue'), ('delivered', 'Totalmente entregue')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('normal', 'Venda normal'), ('deposit', 'Deposito de material')], default='normal', max_length=20),
        ),
    ]
