# Generated by Django 5.2.4 on 2026-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_backfill_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Transferencia'), ('card', 'Cartao'), ('cash', 'Numerario'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('mkesh', 'M-Kesh'), ('other', 'Outro')], max_length=20),
        ),
    ]
