# Generated by Django 5.2.4 on 2026-04-10 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_credit_limit"),
        ("sales", "0009_sale_code"),
        ("tenants", "0018_alter_documentsequence_doc_type_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={
                "permissions": [
                    ("can_backdate_sale", "Pode registar vendas retroativas")
                ]
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="contingency_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sale",
            name="entry_mode",
            field=models.CharField(
                choices=[("normal", "Normal"), ("contingency", "Contingencia")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContingencyBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Aberto"), ("closed", "Fechado")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contingency_batches",
                        to="tenants.business",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_contingency_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_contingency_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="contingency_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="sales.contingencybatch",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["business", "entry_mode", "sale_date"],
                name="sales_sale_busines_41c85f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contingencybatch",
            index=models.Index(
                fields=["business", "status", "date_from", "date_to"],
                name="sales_conti_busines_fa6f28_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contingencybatch",
            constraint=models.UniqueConstraint(
                fields=("business", "code"), name="uniq_contingency_batch_code_business"
            ),
        ),
    ]
