# Generated by Django 5.2.4 on 2026-01-11 10:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_stock_control_mode'),
        ('customers', '0001_initial'),
        ('sales', '0005_sale_delivery_mode_sale_delivery_status_and_more'),
        ('tenants', '0005_alter_business_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_number', models.PositiveBigIntegerField()),
                ('origin_type', models.CharField(choices=[('sale', 'Venda normal'), ('credit', 'Fiado'), ('deposit', 'Deposito de material')], max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('issued', 'Emitida'), ('partial', 'Parcialmente entregue'), ('delivered', 'Totalmente entregue'), ('canceled', 'Cancelada')], default='issued', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_guides', to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_guides', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_guides', to='customers.customer')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_guides', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_guides', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryGuideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.deliveryguide')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='catalog.product')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='sales.saleitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='deliveryguide',
            index=models.Index(fields=['business', 'issued_at'], name='deliveries__busines_8ff317_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryguide',
            index=models.Index(fields=['business', 'status'], name='deliveries__busines_3d0fd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryguide',
            constraint=models.UniqueConstraint(fields=('business', 'guide_number'), name='uniq_delivery_guide_number'),
        ),
        migrations.AddIndex(
            model_name='deliveryguideitem',
            index=models.Index(fields=['guide', 'product'], name='deliveries__guide_i_5822c3_idx'),
        ),
    ]
